{
    dms,
    catppuccin,
    dms-plugin-registry,
    niri-flake,
    ...
}:
{
    imports = [
        catppuccin.homeModules.catppuccin
        dms.homeModules.dank-material-shell
        dms.homeModules.niri
        dms-plugin-registry.modules.default
        niri-flake.homeModules.niri
        niri-flake.homeModules.config
        ./style
        ./dms.nix
        ./niri
    ];
}
