{
    dms,
    catppuccin,
    nix-monitor,
    niri-nix,
    stylix,
    ...
}:
{
    imports = [
        dms.nixosModules.dank-material-shell
        dms.nixosModules.greeter
        catppuccin.nixosModules.catppuccin
        nix-monitor.nixosModules.default
        niri-nix.nixosModules.default
        stylix.nixosModules.stylix
        ./style
        ./dms.nix
        ./niri.nix
    ];
}
